---
baseURL: "https://simplelogin.io/"
languageCode: "en-us"
title: "SimpleLogin | Open source anonymous email service"

enableRobotsTXT: true
canonifyURLs: true
disableKinds:
  - taxonomy
  - taxonomyTerm


# and if you think your md file names or locations might change:
permalinks:
    post: "/blog/:title/"

params:
  description: >
    With email aliases , you can be anonymous online and
    protect your inbox against spams and phishing.
  images:
    - https://simplelogin.io/open-graph.png

markup:
  tableOfContents:
    endLevel: 3
    ordered: true
    startLevel: 3


languages:
  en:
    languageName: "English"
    languageCode: "en_US"
    weight: 1

  fr:
    title: "SimpleLogin | Protéger votre vie privée avec les alias mail"
    languageName: "Français"
    languageCode: "fr"
    weight: 2